#!/usr/bin/env ruby

require 'shellwords'
require 'readline'
require 'fileutils'
require 'socket' # for Socket::get_hostname

class String
	def start_sub!(search, replacement)
		len = search.length
		if self[0, len] == search
			self[0, len] = replacement
		end
		self
	end
	
	# Calculates the length not including ANSI escape codes
	def length_escape
		gsub(/\e\[[0-9;]*m/, '').length
	end
end


module Clam
	class Shell < BasicObject
		def cd(dir=nil)
			dir ||= Dir.home
			::Dir.chdir(dir)
		end
		
		def exit(code=0)
			::Kernel.exit(code.to_i)
		end
		alias_method :quit, :exit
		alias_method :logout, :exit
		
		def set(*args)
			if args.empty?
				$stderr.puts 'usage: set <name=value> ...'
			end
			args.each do |arg|
				name, value = arg.split('=', 2)
				ENV[key] = name
			end
		end
		
		def echo(*args)
			s = args.join(' ')
			$stdout.puts s unless s.empty?
		end
		
		def exec(cmd, *args)
			pid = ::Process.fork {
				begin
					::Kernel.exec(cmd, *args)
				rescue => e
					$stderr.puts e.message
				end
			}
			::Process.wait(pid)
		end
		
		def method_missing(sym, *args)
			exec(sym.to_s, *args)
		end
	end
	
	PROMPT_REPLACEMENTS = {
		'\W' => lambda {
			pwd = Dir.pwd
			pwd.start_sub!(Dir.home, '~')
			pwd
		},
		'\u' => lambda {ENV['USER'] || ''},
		'\h' => lambda {Socket.gethostname},
	}
	
	@@shell = Shell.new
	
	def self.load_config
		config_path = File.join(Dir.home, '.config/clam/config.rb')
		if File.exists?(config_path)
			# This is possibly the most evil Ruby I've ever seen (or written)
			config_source = File.read(config_path)
			@@shell.instance_eval(config_source, config_path)
		else
			# Create the config directory (if needed) and file
			FileUtils.mkdir_p(File.dirname(config_path))
			FileUtils.touch(config_path)
		end
	end
	
	# Runs a clam script
	def self.run(filename)
		file = File.open(filename)
		while line = file.gets
			line.strip!
			args = Shellwords.shellsplit(line)
			execute(args) unless args.empty?
		end
	end
	
	# Read-eval-print-loop
	def self.repl
		input = ''
		loop do
			# Prepare the prompt string
			p = prompt()
			p = ' ' * p.length_escape unless input.empty?
			
			# Read the input line
			begin
				line = Readline.readline(p, true)
			rescue Interrupt
				$stdout.puts
				next
			end
			
			# Process the line
			break unless line
			line.strip!
			input += line
			
			begin
				args = Shellwords.shellsplit(input)
				# BUG
				# `echo '~'` prints "/home/username"
				# should print "'~'"
				args.each {|a| a.start_sub!('~', Dir.home)}
			rescue ArgumentError
				input += "\n"
				next
			end
			
			execute(args) unless args.empty?
			input = ''
		end
		$stdout.puts
	end
	
	# Generates the prompt string
	def self.prompt
		str = String.new(ENV['PROMPT'])
		PROMPT_REPLACEMENTS.each {|k, v| str[k] &&= v.call}
		str
	end
	
	# Runs an array of arguments
	# TODO
	# Support piping and file redirection
	def self.execute(args)
		cmd = args.shift
		
		# Skip comments
		return if cmd.start_with?('#')
		
		@@shell.__send__(cmd, *args)
	end
end



ENV['PROMPT'] ||= "\e[35m\\u@\\h \e[1;34m\\W\e[0;32m =>\e[39m "

Clam.load_config
Clam.repl
